# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'My personal blog for imtaqin.id'
    twitter: 'fdciabdul'
    analytics:
    google_analytics: 'UA-255507505-1'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
    verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Me.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'


features:
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'giscus'
    giscus:
      repo: 'fdciabdul/imtaqin.id'
      repo_id: 'R_kgDOL6WiKA'
      category: 'Q&A'
      category_id: 'DIC_kwDOL6WiKM4CfVzs'
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname
    disqus:
      # Paste the shortname from your Disqus dashboard.
      shortname: ''
      # Show comment count in page header? (true/false)
      show_count: true
    commento:
      # If you self-host Commento, enter your custom Commento URL here.
      url: ''